package qpay

// MCC is a Merchant Category Code recognised by QPay.
// NameMongolian is the Cyrillic Mongolian display name supplied by QPay.
type MCC struct {
	Code          string `json:"mcc_code"`
	NameMongolian string `json:"name_mon"`
}

// MCCCodes is the canonical list of QPay-supported merchant category codes.
// Sourced from the QPay merchant onboarding catalogue. Sorted by code (string order).
//
// Use MCCByCode for O(1) lookup when validating a code chosen by a user.
var MCCCodes = []MCC{
	{Code: "742", NameMongolian: "Мал эмнэлгийн үйлчилгээ"},
	{Code: "780", NameMongolian: "Орчны тохижилтын үйлчилгээ"},
	{Code: "1740", NameMongolian: "Чулуун буюу тоосгон өрлөг, засал чимэглэлийн үйлчилгээ"},
	{Code: "2741", NameMongolian: "Төрөл бүрийн хэвлэх, хувилах үйлчилгээ"},
	{Code: "2791", NameMongolian: "Үсэг өрөх, хэв бэлдэх үйлчилгээ"},
	{Code: "2842", NameMongolian: "Цэвэрлэгээ үйлчилгээ"},
	{Code: "4011", NameMongolian: "Төмөр замын ачаа тээвэр"},
	{Code: "4112", NameMongolian: "Төмөр замын зорчигч тээвэр"},
	{Code: "4119", NameMongolian: "Түргэн тусламжийн үйлчилгээ"},
	{Code: "4131", NameMongolian: "Автобусны шугамын үйлчилгээ"},
	{Code: "4214", NameMongolian: "Том оврын ачааны машины үйлчилгээ - нүүлгэлт, хүргэлт"},
	{Code: "4215", NameMongolian: "Шуудангийн үйлчилгээ"},
	{Code: "4225", NameMongolian: "Агуулах болон хадгалалтын үйлчилгээ"},
	{Code: "4511", NameMongolian: "Агаарын ачаа болон зорчигч тээвэр"},
	{Code: "4582", NameMongolian: "Тийз"},
	{Code: "4722", NameMongolian: "Аялал жуулчлал"},
	{Code: "4789", NameMongolian: "Бусад тээврийн үйлчилгээ"},
	{Code: "4812", NameMongolian: "Гар утас худалдаа"},
	{Code: "4814", NameMongolian: "Харилцаа холбооны үйлчилгээ"},
	{Code: "4816", NameMongolian: "Компьютер, гар утас худалдаа"},
	{Code: "4821", NameMongolian: "Цахилгаан холбооны үйлчилгээ"},
	{Code: "5013", NameMongolian: "Авто сэлбэг"},
	{Code: "5021", NameMongolian: "Оффисын тавилга"},
	{Code: "5039", NameMongolian: "Барилгын материал"},
	{Code: "5172", NameMongolian: "Шатахуун түгээх"},
	{Code: "5192", NameMongolian: "Бичиг хэрэг"},
	{Code: "5193", NameMongolian: "Гэр ахуйн бараа"},
	{Code: "5200", NameMongolian: "Гэр ахуйн барааны дэлгүүр"},
	{Code: "5211", NameMongolian: "Модон эдлэл, барилгын материалын дэлгүүр"},
	{Code: "5231", NameMongolian: "Нүдний шил"},
	{Code: "5251", NameMongolian: "Техник хэрэгслийн дэлгүүр"},
	{Code: "5261", NameMongolian: "Зүлэгжүүлэлт, цэцэрлэгжүүлэлтийн барааны дэлгүүр"},
	{Code: "5300", NameMongolian: "Бөөний худалдаа"},
	{Code: "5309", NameMongolian: "Татваргүй барааны дэлгүүр"},
	{Code: "5310", NameMongolian: "Хямдралтай барааны дэлгүүр"},
	{Code: "5311", NameMongolian: "Их дэлгүүр"},
	{Code: "5331", NameMongolian: "Төрөлжсөн бус барааны дэлгүүр"},
	{Code: "5399", NameMongolian: "Бусад бараа бүтээгдэхүүний худалдаа"},
	{Code: "5411", NameMongolian: "Хүнсний дэлгүүр, супермаркет"},
	{Code: "5422", NameMongolian: "Мах, махан бүтээгдэхүүний нийлүүлэлт"},
	{Code: "5441", NameMongolian: "Чихэр, самар, амттаны дэлгүүр"},
	{Code: "5451", NameMongolian: "Сүү, сүүн бүтээгдэхүүний дэлгүүр"},
	{Code: "5499", NameMongolian: "Bakery"},
	{Code: "5521", NameMongolian: "Хуучин моторт тээврийн хэрэгслийн худалдаа, үйлчилгээ, сэлбэг болон түрээс"},
	{Code: "5531", NameMongolian: "Автомашин болон гэр ахуйн барааны дэлгүүр"},
	{Code: "5532", NameMongolian: "Автомашины дугуйны дэлгүүр"},
	{Code: "5533", NameMongolian: "Автомашины сэлбэг, жижиг хэрэгслийн дэлгүүр"},
	{Code: "5561", NameMongolian: "Мотоциклийн дэлгүүр, худалдаа"},
	{Code: "5592", NameMongolian: "Зөөврийн сууцны худалдаа"},
	{Code: "5611", NameMongolian: "Эрэгтэйчүүдийн хувцас, хэрэглэлийн төрөлжсөн дэлгүүр"},
	{Code: "5621", NameMongolian: "Эмэгтэйчүүдийн хувцасны төрөлжсөн дэлгүүр"},
	{Code: "5631", NameMongolian: "Эмэгтэй гоёл, зүүлт"},
	{Code: "5641", NameMongolian: "Хүүхэд болон нярайн хувцас хэрэглэлийн дэлгүүр"},
	{Code: "5651", NameMongolian: "Гэр бүлийн хувцасны дэлгүүр"},
	{Code: "5655", NameMongolian: "Спорт хувцасны дэлгүүр"},
	{Code: "5661", NameMongolian: "Гутлын дэлгүүр"},
	{Code: "5681", NameMongolian: "Үслэг эдлэлийн дэлгүүр"},
	{Code: "5698", NameMongolian: "Хиймэл үсний дэлгүүр"},
	{Code: "5699", NameMongolian: "Бусад эдлэл хэрэглэл, гоёл чимэглэлийн дэлгүүр"},
	{Code: "5712", NameMongolian: "Гэрийн тавилга, цахилгаан бараанаас бусад ахуйн барааны дэлгүүр"},
	{Code: "5713", NameMongolian: "Хивс, хивсэнцэр, шалны дэвсгэрийн дэлгүүр"},
	{Code: "5714", NameMongolian: "Бөс бараа, хөшиг, бүрээсний дэлгүүр"},
	{Code: "5718", NameMongolian: "Зуух, зуухны хамгаалалт, жижиг хэрэгслийн дэлгүүр"},
	{Code: "5719", NameMongolian: "Бусад гэр ахуйн төрөлжсөн барааны дэлгүүр"},
	{Code: "5722", NameMongolian: "Гэр ахуйн цахилгаан барааны дэлгүүр"},
	{Code: "5732", NameMongolian: "Цахилгаан бараа"},
	{Code: "5733", NameMongolian: "Хөгжмийн дэлгүүр - хөгжмийн зэмсэг, төгөлдөр хуур, нот"},
	{Code: "5734", NameMongolian: "Компьютерийн програм хангамжийн дэлгүүр"},
	{Code: "5735", NameMongolian: "Дуу бичлэг, хуурцаг, CD, DVD-ний дэлгүүр"},
	{Code: "5812", NameMongolian: "Хоолны газар, ресторан"},
	{Code: "5813", NameMongolian: "Шөнийн цэнгээний газар, паб"},
	{Code: "5912", NameMongolian: "Эм, гоо сайхан, ариун цэврийн барааны дэлгүүр"},
	{Code: "5921", NameMongolian: "Шар айраг, вино, архины төрөлжсөн дэлгүүр"},
	{Code: "5931", NameMongolian: "Хуучин барааны дэлгүүр"},
	{Code: "5932", NameMongolian: "Шашны бараа"},
	{Code: "5937", NameMongolian: "Эртний эдлэл засварлах үйлчилгээ"},
	{Code: "5940", NameMongolian: "Унадаг дугуйн дэлгүүр"},
	{Code: "5941", NameMongolian: "Спорт барааны дэлгүүр"},
	{Code: "5942", NameMongolian: "Номын дэлгүүр"},
	{Code: "5943", NameMongolian: "Бичиг хэрэг, оффисын хангамж, бичгийн болон хэвлэлийн цаасны дэлгүүр"},
	{Code: "5944", NameMongolian: "Алт мөнгөн эдлэл, гоёл чимэглэл"},
	{Code: "5945", NameMongolian: "Тоглоомын дэлгүүр"},
	{Code: "5946", NameMongolian: "Гэрэл зургийн аппарат, холбогдох хэрэгслийн дэлгүүр"},
	{Code: "5947", NameMongolian: "Бэлэг, мэндчилгээ, бэлэг дурсгалын дэлгүүр"},
	{Code: "5948", NameMongolian: "Аяллын цүнх, арьсан бүтээгдэхүүний дэлгүүр"},
	{Code: "5949", NameMongolian: "Бөс бараа, оѐдлын барааны дэлгүүр"},
	{Code: "5950", NameMongolian: "Шилэн эдлэлийн дэлгүүр"},
	{Code: "5970", NameMongolian: "Уран зураг, гар урлалын хэрэгслийн дэлгүүр"},
	{Code: "5971", NameMongolian: "Галарей, уран зургийн худалдаа"},
	{Code: "5972", NameMongolian: "Тамга, зоосны дэлгүүр"},
	{Code: "5973", NameMongolian: "Шашны эдлэл хэрэглэлийн дэлгүүр"},
	{Code: "5975", NameMongolian: "Сонсголын аппарат, дагалдах хэрэгслийн худалдаа"},
	{Code: "5976", NameMongolian: "Согог заслын бүтээгдэхүүн худалдаа"},
	{Code: "5977", NameMongolian: "Гоо сайхны барааны дэлгүүр"},
	{Code: "5992", NameMongolian: "Цэцгийн дэлгүүр"},
	{Code: "5993", NameMongolian: "Тамхины төрөлжсөн дэлгүүр болон цэг"},
	{Code: "5994", NameMongolian: "Сонин сэтгүүлийн худалдаа"},
	{Code: "5995", NameMongolian: "Тэжээвэр амьтан, амьтны хоол, жижиг хэрэгслийн дэлгүүр"},
	{Code: "5998", NameMongolian: "Майхан, сүүдрэвчний дэлгүүр"},
	{Code: "5999", NameMongolian: "Бусад төрөлжсөн барааны дэлгүүр"},
	{Code: "6010", NameMongolian: "Банк бус"},
	{Code: "6012", NameMongolian: "Ломбард"},
	{Code: "6300", NameMongolian: "Даатгалын компани"},
	{Code: "7011", NameMongolian: "Зочид буудал"},
	{Code: "7210", NameMongolian: "Угаалга, цэвэрлэгээний үйлчилгээ"},
	{Code: "7216", NameMongolian: "Хими цэвэрлэгээ"},
	{Code: "7261", NameMongolian: "Оршуулга, чандарлах үйлчилгээ"},
	{Code: "7276", NameMongolian: "Татварын зөвлөгөө өгөх үйлчилгээ"},
	{Code: "7277", NameMongolian: "Зөвлөгөө өгөх үйлчилгээ"},
	{Code: "7298", NameMongolian: "Эрүүл мэнд, гоо сайхны үйлчилгээ"},
	{Code: "7299", NameMongolian: "Бусад үйлчилгээ"},
	{Code: "7311", NameMongolian: "Зар сурталчилгааны үйлчилгээ"},
	{Code: "7342", NameMongolian: "Устгалын үйлчилгээ"},
	{Code: "7349", NameMongolian: "Цэвэрлэгээ, арчилгаа"},
	{Code: "7372", NameMongolian: "Компьютерын програмчлалын үйлчилгээ"},
	{Code: "7375", NameMongolian: "Мэдээллийн лавлах үйлчилгээ"},
	{Code: "7379", NameMongolian: "Компьютер засварын үйлчилгээ"},
	{Code: "7392", NameMongolian: "Зөвлөх, олон нийттэй харилцах үйлчилгээ"},
	{Code: "7394", NameMongolian: "Тоног төхөөрөмжийн түрээсийн үйлчилгээ"},
	{Code: "7395", NameMongolian: "Зураг засварын үйлчилгээ"},
	{Code: "7399", NameMongolian: "Бусад бизнесийн үйлчилгээ"},
	{Code: "7513", NameMongolian: "Том оврын машин, чиргүүл түрээслэх үйлчилгээ"},
	{Code: "7534", NameMongolian: "Авто засварын газар"},
	{Code: "7535", NameMongolian: "Автомашин будаж засах үйлчилгээ"},
	{Code: "7542", NameMongolian: "Авто угаалга"},
	{Code: "7549", NameMongolian: "Ачих, чирэх үйлчилгээ"},
	{Code: "7832", NameMongolian: "Кино Театр"},
	{Code: "7911", NameMongolian: "Бүжгийн танхим, студи, сургууль"},
	{Code: "7941", NameMongolian: "Фитнесс"},
	{Code: "7994", NameMongolian: "Интэрнет кафе"},
	{Code: "7997", NameMongolian: "Гольф"},
	{Code: "8011", NameMongolian: "Эмч"},
	{Code: "8021", NameMongolian: "Шүдний эмч"},
	{Code: "8041", NameMongolian: "Бариа засал"},
	{Code: "8043", NameMongolian: "Нүдний эмч, нүдний шилний газар"},
	{Code: "8049", NameMongolian: "Хөлийн эрүүл мэнд, эмчилгээ"},
	{Code: "8050", NameMongolian: "Асаргаа, сувилгааны газар"},
	{Code: "8062", NameMongolian: "Эмнэлэг"},
	{Code: "8071", NameMongolian: "Эрүүл мэнд, шүдний лаборатори"},
	{Code: "8099", NameMongolian: "Эрүүл мэндийн үйлчилгээ"},
	{Code: "8111", NameMongolian: "Хуулийн зөвлөгөө, өмгөөллийн үйлчилгээ"},
	{Code: "8211", NameMongolian: "Сургалтын төв"},
	{Code: "8220", NameMongolian: "Их дээд сургууль"},
	{Code: "8241", NameMongolian: "Эчнээ сургууль"},
	{Code: "8244", NameMongolian: "Бизнесийн сургууль"},
	{Code: "8249", NameMongolian: "Мэргэжил олгох сургууль"},
	{Code: "8299", NameMongolian: "Гадаад хэлний сургалт"},
	{Code: "8351", NameMongolian: "Хүүхдийн цэцэрлэг"},
	{Code: "8398", NameMongolian: "Буяны байгууллага болон хандив цуглуулах үйл ажиллагаа"},
	{Code: "8641", NameMongolian: "Иргэдийн, нийгмийн, ах дүүсийн нийгэмлэг"},
	{Code: "8651", NameMongolian: "Улс төрийн байгууллага"},
	{Code: "8661", NameMongolian: "Шашны байгууллага"},
	{Code: "8675", NameMongolian: "Автомашин сонирхогчдын холбоо"},
	{Code: "8699", NameMongolian: "Гишүүнчлэлийн байгууллага"},
	{Code: "8734", NameMongolian: "Шинжилгээ судалгааны лаборатори"},
	{Code: "8911", NameMongolian: "Архитектур зураг төслийн үйлчилгээ"},
	{Code: "8931", NameMongolian: "Нягтлан бодох бүртгэлийн үйлчилгээ"},
	{Code: "8999", NameMongolian: "Мэргэжлийн үйлчилгээ"},
	{Code: "9222", NameMongolian: "Төрийн үйлчилгээний торгууль"},
	{Code: "9311", NameMongolian: "Татвар төлөлт"},
	{Code: "9399", NameMongolian: "Төрийн бусад үйлчилгээ"},
	{Code: "9402", NameMongolian: "Шуудангийн салбар"},
}

// mccIndex is built once at package init for O(1) lookups.
var mccIndex = func() map[string]MCC {
	m := make(map[string]MCC, len(MCCCodes))
	for _, c := range MCCCodes {
		m[c.Code] = c
	}
	return m
}()

// MCCByCode returns the MCC entry for a given code.
// The second return is false if the code is unknown.
func MCCByCode(code string) (MCC, bool) {
	m, ok := mccIndex[code]
	return m, ok
}

// IsValidMCC reports whether the given code appears in the QPay-supported MCC list.
func IsValidMCC(code string) bool {
	_, ok := mccIndex[code]
	return ok
}
